server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - bus-refresh
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aditya-mittal/config-repo
          basedir: target/config
    bus:
      enabled: true

---
spring:
  profiles: cloud